# docker-compose.yml
version: '3'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - ./uploads:/app/uploads
    environment:
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD=password
      - DB_NAME=file_sharing
      - DB_PORT=3306
      - JWT_SECRET=your_jwt_secret
    depends_on:
      - db
    restart: on-failure

  db:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=file_sharing
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: